#!/bin/bash

# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

$OPENSHIFT_DATA_DIR/bin/python $OPENSHIFT_REPO_DIR/server.py >$OPENSHIFT_LOG_DIR/python_log.txt & echo $! >> $OPENSHIFT_DATA_DIR/pid.txt &
